[colors]
[colors.primary]
background = "#121212"
foreground = "#E6E3D9"
dim_foreground = "#FFF9B9"

[colors.cursor]
text = "#121212"
cursor = "#ffffff"

[colors.selection]
text = "CellForeground"
background = "#333333"

[colors.normal]
black = "#333333"
blue = "#bef50a"
cyan = "#ffeb07"
green = "#EC5B5B"
magenta = "#FFF9B9"
red = "#EC5B5B"
white = "#A09E97"
yellow = "#E6E3D9"

[colors.bright]
black = "#FFEB07"
blue = "#DCFFB2"
cyan = "#EC5B5B"
green = "#A1D8FF"
magenta = "#FF81C8"
red = "#FFE8E8"
white = "#FFEB07"
yellow = "#DCFFB2"
