-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")

-- NOTE: LazyVim handles format-on-save automatically through conform.nvim
-- The custom autocmd below is commented out to avoid conflicts
-- If LazyVim's autoformat is disabled, uncomment this:

-- -- Format on save with Biome
-- local format_group = vim.api.nvim_create_augroup("BiomeFormatting", { clear = true })
--
-- vim.api.nvim_create_autocmd("BufWritePre", {
--   group = format_group,
--   pattern = { "*.ts", "*.tsx", "*.js", "*.jsx", "*.json", "*.jsonc" },
--   callback = function(args)
--     require("conform").format({ bufnr = args.buf, timeout_ms = 2000 })
--   end,
--   desc = "Format with Biome on save",
-- })
