add_newline = true
command_timeout = 200
format = "$username$hostname$git_branch$git_status\n$directory $character"

[username]
show_always = true
format = "[$user](bold blue)[@](bold cyan)"

[hostname]
ssh_only = false
format = "[$hostname](bold cyan)[: ](bold cyan)"

[character]
error_symbol = "[\\$](bold red)"
success_symbol = "[\\$](bold green)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
style = "bold blue"
repo_root_style = "bold blue"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)"

[git_branch]
format = "[git](bold cyan)[\\(](bold red)[$branch](bold yellow)[\\)](bold red)"
style = "bold yellow"

[git_status]
format = '[$all_status$ahead_behind](bold red)'
style = "bold red"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = ""
untracked  = " "
modified   = " "
stashed    = " "
staged     = " "
renamed    = " "
deleted    = " "
