add_newline = true
command_timeout = 200
format = "$username$directory[ →](bold cyan)$git_branch$git_status$character"

[username]
show_always = true
format = "[$user](bold blue)[@](bold cyan)"

[character]
error_symbol = "[ ❯](bold red)"
success_symbol = "[ ❯](bold green)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
style = "bold cyan"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)"

[git_branch]
format = "[ git:](bold cyan)[\\(](bold yellow)[$branch](bold yellow)[\\)](bold yellow)"
style = "bold yellow"

[git_status]
format = '[ $all_status$ahead_behind](bold red)'
style = "bold red"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = ""
untracked  = " "
modified   = " "
stashed    = " "
staged     = " "
renamed    = " "
deleted    = " "
